config/routes.rb
Bloga::Application.routes.draw do
  devise_for :users, :controllers => {:sessions => 'sessions'},  skip: [:registrations, :sessions]
  devise_scope :user do
    get '/signin'   => "sessions#new",       :as => :new_user_session
    post '/signin'  => 'sessions#create',    :as => :user_session
    get '/signout'  => 'sessions#destroy',   :as => :destroy_user_session
    get "/signup"   => "users#new",   :as => :new_user_registration
   end

  resources :users
  resources  :sessions 
  
  resources :notes

  resources :note_books

  resources :posts do
      resources :comments
  end
  
  match '/new', to: 'posts#about', via: :get
  match '/show', to: 'posts#show', via: :get
  
  root "users#index"

  

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  #source in app/models/concerns
  include TokenAuthenticatable
  
  #added via  activerecord-mongoid-association gem
  include AddsHasManyMongoidToActiveRecord
  
  has_many_mongoid_documents :note_books
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_users, only: [:show, :edit, :update, :destroy]
  
  # This is our new function that comes before Devise's one
  before_filter :authenticate_user_from_token!, except: [:new, :create]
  
  before_filter :authenticate_user!, except: [:new, :create]
  
  
  #skip_before_filter :verify_authenticity_token, :only => :create
  
  respond_to :json, :html

  def index
   @users = User.all
    respond_with @users
  end
  
  def edit
  end
   
  def show
  end
  
  def new
    @user = User.new
    respond_with @user
  end
  
  def create
    @user = User.new(user_params)
    @user.reset_authentication_token!
    if @user.save
      sign_in :user, @user
      #respond_with @user
      
      render json: @user
    else
      render "new"
    end
  end
  
  def update
    if params[:user][:password].blank?
      params[:user].delete("password")
      params[:user].delete("password_confirmation")
    end
    if @user.update(user_params)
      @user.reset_authentication_token!
      sign_in :user, @user, bypass: true
     
      respond_with @user
    else
      render "edit"
    end
  end
  
  
  def destroy
    @user.destroy
    respond_with @user
  end
  
  private
  
  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :authentication_token)
  end
  
  def set_users
    @user = User.find(params[:id])
    respond_with @user
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<div class="row">
  
  <%= form_for @user do |f| %>
  
   <% if @user.errors.any? %>
    <div id="error_explanation" class="alert-danger">
      <h2><%= pluralize(@user.errors.count, "error") %>
        prohibited this user from being saved:</h2>
      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
    <% end %>
  
    <fieldset>
      <legend>Registration form </legend>
      
      <div class="col-lg-8">
        <div class="form-group">
          <label class="control-label"><%= f.label :email %></label>
          <div class="form-control"><%= f.email_field :email %></div>
        </div>
      </div>
      
      <div class="col-lg-8">
        <div class="form-group">
          <label class="control-label"><%= f.label :password %> </label>
          <div class="form-control"><%= f.password_field :password%> </div>
        </div>
      </div>
      
       <div class="col-lg-8">
        <div class="form-group">
          <label class="control-label"><%= f.label :password_confirmation %> </label>
          <div class="form-control"><%= f.password_field :password_confirmation%> </div>
        </div>
      </div>
      
      <div class="col-lg-8">
        <div class="form-group">
          <div class="btn btn-primary">
            <%= f.submit "Sign Up" %>
          </div>
        </div>
      </div>
      
       <%= link_to "Forgot your password?", new_password_path(@user) %><br />      
      
    </fieldset>
  <% end %> 
</div>

app/views/users/show.html.erb
show page